version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.6.0
    steps:
      - run:
          name: Print environment versions
          command: |
            NODE_V=$(node -v)
            echo node version':' $NODE_V
            NPM_V=$(npm -v)
            echo npm version':' $NPM_V
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Package Install
          command: |
            echo -e "$NPM_USER\n$NPM_PWD\n$NPM_EMAIL" | npm login --scope=@ssv
            npm i
            npm i gulp -g
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
      - deploy:
          name: Publish NPM
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ]; then
              echo -e "\e[33m Branch does not publish -- exit!"
              exit
            fi
            . ./.circleci/utils.sh
           
            PACKAGE_VERSION=$(node -p "require('./package.json').version")
            
            print_title "publish..."
            npm publish --access=public

            print_title "git tag"
            git tag $PACKAGE_VERSION
            git push --tags